version: '2.1'
services:
  app:
    image: maestroalubia/ftp-to-nextcloud
    ports:
      - "${EXTERNAL_PORT:-127.0.0.1:20-21}:20-21"
      - "${EXTERNAL_PASV_PORT:-127.0.0.1:1025-1050}:1025-1050"
    environment:
      - FTP_HOSTNAME=${FTP_HOSTNAME}
    volumes:
      - /home/ftp:/ftp
    restart: 'always'
