version: '2.1'
services:
  app:
    image: maestroalubia/ftp-to-nextcloud
    ports:
      - "${EXTERNAL_DATA_PORT:-127.0.0.1:20}:20"
      - "${EXTERNAL_CONTROL_PORT:-127.0.0.1:21}:21"
      - "${EXTERNAL_PASV_PORT:-127.0.0.1:1025}:1025"
    environment:
      - FTP_HOSTNAME=${FTP_HOSTNAME}
    volumes:
      - /home/ftp:/ftp
    restart: 'always'
